### ISSUE TITLE
Export current hasura metadata

### ISSUE THREAD

**Issue by radowit** [zagrajmy/app#127]
Hi, please export the hasura metadata that you configured to work on frontend tasks and commit it on backend repo, as described in https://github.com/zagrajmy/zm-backend/pull/24

**Comment by hasparus** [comment]
I'll wait for https://github.com/zagrajmy/zm-backend/pull/23.

BTW I'm still seeing `meetings_` instead of `nb_` (as in code). Did the deploy work?

http://35.204.239.210:8080/console/api-explorer

**Comment by radowit** [comment]
I think you need to recreate your db, but wait with it for the merge of PR #23

**Comment by radowit** [comment]
All hasura-related stuff is merged now.
Please recreate your docker environment and try now.
